// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


let n = 0;
let sum2 = 0;
let a = 1;
let b = 2;

while (n < 4000000) {
	if (a % 2 == 0)
		sum2 += a;
	if (b % 2 == 0)
		sum2 += b;
	a +=  b;
	b += a;
	n += a;
}

document.getElementById("problem2").innerHTML = sum2;